### ISSUE TITLE
A doubt about the derivation of formulas in the paper

### ISSUE THREAD

**Issue by TianQi-777** [YisenWang/MART#1]
Thank you for your sharing!
I would like to ask a question about the derivation of formulas in the paper. Specifically, I don't know the derivation of the last two steps of formula (7) in the paper.
It seems that `1(h_theta(x_i)=y_i)=1` and `1(h_theta(x_adv_i)!=y_i)=0`, so that we can infer from the penultimate line to the last line, But why?

**Comment by YisenWang** [comment]
I give more detailed derivations of Eq. 7. Please copy and paste in a latex environment to view. 

\begin{align}\label{eq:loss_func_indicator}
\textstyle{\min_\btheta
\cR_{\text{misc}}(h_\btheta)} :&= \textstyle{\frac{1}{n}\Big(\sum_{i\in\cS_{h_{\btheta}}^+}\cR^{+}(h_{\btheta}, \xb_i) + \sum_{i\in\cS_{h_{\btheta}}^-}\cR^{-}(h_{\btheta}, \xb_i)\Big)}\notag\\
&=\textstyle{\frac{1}{n}\sum_{i=1}^n\big\{ \ind(h_{\btheta}(\xb_i)= y_i)\cdot R^+(h_{\btheta},\xb_i)  + \ind(h_{\btheta}(\xb_i)\neq y_i)\cdot R^-(h_{\btheta},\xb_i)\big\}}\notag\\
&=\textstyle{\frac{1}{n}\sum_{i=1}^n\big\{ \ind(h_{\btheta}(\xb_i)= y_i)\cdot \ind(h_{\btheta}(\hat\xb_i')\neq y_i)  }\notag\\
&\qquad \textstyle{+ \ind(h_{\btheta}(\xb_i)\neq y_i)\cdot\big(\ind(h_{\btheta}(\hat\xb_i')\neq y_i)+ \ind( h_{\btheta}(\xb_i)\neq h_{\btheta}(\hat\xb_i'))\big)\big\}}\notag\\
& = \textstyle{\frac{1}{n} \sum_{i=1}^n\big\{ \ind(h_{\btheta}(\hat\xb_i')\neq y_i)  + \ind (h_{\btheta}(\xb_i)\neq h_{\btheta}(\hat\xb_i')) \cdot \ind(h_{\btheta}(\xb_i)\neq y_i)\big\}},
\end{align}

**Comment by TianQi-777** [comment]
Thank you for your reply, but it looks like the code is wrong!
Can you send the pictures to my E-mail? tianqi95a@hotmail.com
Thank you very much!

**Comment by YisenWang** [comment]
Would you please point out which is wrong? I have attached a picture here
<img width="449" alt="eq7" src="https://user-images.githubusercontent.com/23697768/76844988-191ec580-6879-11ea-81e0-43ffb227e143.png">

**Comment by TianQi-777** [comment]
I mean that your latex code is not displayed correctly in my editor, not that the formula in your paper is wrong.
Actually, my problem is shown below
<img width="555" alt="图片1" src="https://user-images.githubusercontent.com/30693632/76874182-c7dafa00-68a9-11ea-8599-c87f3d56f07c.PNG">
Looking forward to your reply

**Comment by YisenWang** [comment]
Expand and merge......

**Comment by TianQi-777** [comment]
Got it, sorry, I was careless and thanks for your quick reply :)
