### ISSUE TITLE
https://mega.nz/#!xZ8glS6J!MAnE91ND_WyfZ_8mvkuSa2YcA7q-1ehfSm-Q1fxOvvs  can not be accessed in China

### ISSUE THREAD

**Issue by aspnetcs** [YisenWang/MART#4]
https://mega.nz/#!xZ8glS6J!MAnE91ND_WyfZ_8mvkuSa2YcA7q-1ehfSm-Q1fxOvvs  can not be accessed in China

**Comment by aspnetcs** [comment]
I found it in baidu cloud disk.

**Comment by YisenWang** [comment]
Sorry, I did not get your meaning. Actually, I did not click the unknown link due to the security concern.
